name: ml_project
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cycler=0.10.0
  - ffmpeg=4.3
  - freetype=2.10.4
  - gettext=0.19.8.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - jpeg=9b
  - kiwisolver=1.3.1
  - lame=3.100
  - lcms2=2.11
  - libcxx=10.0.0
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - llvm-openmp=11.1.0
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.0.2
  - ncurses=6.2
  - nettle=3.4.1
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1j
  - pillow=8.1.2
  - pip=21.0.1
  - pyparsing=2.4.7
  - python=3.9.1
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytorch=1.8.0
  - readline=8.1
  - scipy=1.6.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.2
  - tk=8.6.10
  - torchaudio=0.8.0
  - torchvision=0.9.0
  - tornado=6.1
  - typing_extensions=3.7.4.3
  - tzdata=2020f
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - chardet==4.0.0
    - idna==2.10
    - joblib==1.0.1
    - pygame==2.0.1
    - requests==2.25.1
    - scikit-learn==0.24.1
    - threadpoolctl==2.1.0
    - tqdm==4.59.0
    - urllib3==1.26.4
