AGENT_NAME_KEY = 'AGENT_NAME'

LEARNING_RATE_KEY = 'LEARNING_RATE'
DISCOUNT_FACTOR_KEY = 'DISCOUNT_FACTOR'

# TODO: Add policy type and corresponding settings

UPDATE_ALGORITHM_KEY = 'UPDATE_ALGORITHM'

NUM_SARSA_STEPS_KEY = 'NUM_SARSA_STEPS'

TRACE_DECAY_KEY = 'TRACE_DECAY'
